-- Runs against H2 in Oracle-compatibility mode for local development.
-- See schema-oracle.sql for the real Oracle DDL you'd run against an actual instance.

DROP TABLE IF EXISTS work_spec_catalog;

CREATE TABLE work_spec_catalog (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_code      VARCHAR(50)  NOT NULL,
    network_type      VARCHAR(20)  NOT NULL,
    work_spec_code    VARCHAR(50)  NOT NULL,
    description       VARCHAR(200),
    duration_minutes  INT,
    required_skill    VARCHAR(50)
);
