-- Real Oracle DDL. Run this with SQL*Plus, SQLcl, or a DB tool against an
-- actual Oracle instance (e.g. Oracle XE running in Docker at home).
-- Not used automatically by the app under the "h2" profile.

DROP TABLE work_spec_catalog CASCADE CONSTRAINTS;

CREATE TABLE work_spec_catalog (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_code      VARCHAR2(50)  NOT NULL,
    network_type      VARCHAR2(20)  NOT NULL,
    work_spec_code    VARCHAR2(50)  NOT NULL,
    description       VARCHAR2(200),
    duration_minutes  NUMBER(5),
    required_skill    VARCHAR2(50)
);

CREATE INDEX idx_wsc_service_network ON work_spec_catalog (service_code, network_type);

-- See data.sql for INSERT statements; the syntax is portable between
-- Oracle and H2 for this simple table, so the same inserts work against
-- a real Oracle instance too.
