-- Runs against H2 in Oracle-compatibility mode for local development.
-- See schema-oracle.sql for the real Oracle DDL you'd run against an actual instance.

DROP TABLE IF EXISTS work_order_spec;
DROP TABLE IF EXISTS work_order;
DROP TABLE IF EXISTS provisioning_request;
DROP TABLE IF EXISTS work_spec_catalog;

CREATE TABLE work_spec_catalog (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_code      VARCHAR(50)  NOT NULL,
    network_type      VARCHAR(20)  NOT NULL,
    work_spec_code    VARCHAR(50)  NOT NULL,
    description       VARCHAR(200),
    duration_minutes  INT,
    required_skill    VARCHAR(50)
);

-- Every incoming request, valid or not, with its raw JSON and final outcome.
CREATE TABLE provisioning_request (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          VARCHAR(100),
    customer_id       VARCHAR(100),
    request_type      VARCHAR(100),
    payload           CLOB         NOT NULL,
    status            VARCHAR(20)  NOT NULL,  -- RECEIVED, COMPLETED, REJECTED, FAILED
    status_detail     CLOB,                    -- rule violations or error message
    received_at       TIMESTAMP    NOT NULL,
    completed_at      TIMESTAMP
);

CREATE INDEX idx_pr_order_id ON provisioning_request (order_id);

-- Dispatchable work orders produced by step 5 for a completed request.
CREATE TABLE work_order (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id        BIGINT       NOT NULL REFERENCES provisioning_request (id),
    work_order_number VARCHAR(150) NOT NULL,  -- e.g. ORD-1001-WO1
    dispatch_group    VARCHAR(100) NOT NULL,
    sequence_no       INT          NOT NULL,
    created_at        TIMESTAMP    NOT NULL,
    CONSTRAINT uq_wo_request_number UNIQUE (request_id, work_order_number)
);

-- The work specs grouped under each work order.
CREATE TABLE work_order_spec (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id     BIGINT       NOT NULL REFERENCES work_order (id),
    line_no           INT          NOT NULL,
    work_spec_code    VARCHAR(50)  NOT NULL,
    description       VARCHAR(200),
    duration_minutes  INT,
    required_skill    VARCHAR(50)
);
