-- Real Oracle DDL. Run this with SQL*Plus, SQLcl, or a DB tool against an
-- actual Oracle instance (e.g. Oracle XE running in Docker at home).
-- Not used automatically by the app under the "h2" profile.

DROP TABLE work_order_spec CASCADE CONSTRAINTS;
DROP TABLE work_order CASCADE CONSTRAINTS;
DROP TABLE provisioning_request CASCADE CONSTRAINTS;
DROP TABLE work_spec_catalog CASCADE CONSTRAINTS;

CREATE TABLE work_spec_catalog (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    service_code      VARCHAR2(50)  NOT NULL,
    network_type      VARCHAR2(20)  NOT NULL,
    work_spec_code    VARCHAR2(50)  NOT NULL,
    description       VARCHAR2(200),
    duration_minutes  NUMBER(5),
    required_skill    VARCHAR2(50)
);

CREATE INDEX idx_wsc_service_network ON work_spec_catalog (service_code, network_type);

-- Every incoming request, valid or not, with its raw JSON and final outcome.
CREATE TABLE provisioning_request (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id          VARCHAR2(100),
    customer_id       VARCHAR2(100),
    request_type      VARCHAR2(100),
    payload           CLOB          NOT NULL,
    status            VARCHAR2(20)  NOT NULL,  -- RECEIVED, COMPLETED, REJECTED, FAILED
    status_detail     CLOB,                     -- rule violations or error message
    received_at       TIMESTAMP     NOT NULL,
    completed_at      TIMESTAMP
);

CREATE INDEX idx_pr_order_id ON provisioning_request (order_id);

-- Dispatchable work orders produced by step 5 for a completed request.
CREATE TABLE work_order (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id        NUMBER        NOT NULL REFERENCES provisioning_request (id),
    work_order_number VARCHAR2(150) NOT NULL,  -- e.g. ORD-1001-WO1
    dispatch_group    VARCHAR2(100) NOT NULL,
    sequence_no       NUMBER(5)     NOT NULL,
    created_at        TIMESTAMP     NOT NULL,
    CONSTRAINT uq_wo_request_number UNIQUE (request_id, work_order_number)
);

CREATE INDEX idx_wo_request ON work_order (request_id);

-- The work specs grouped under each work order.
CREATE TABLE work_order_spec (
    id                NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id     NUMBER        NOT NULL REFERENCES work_order (id),
    line_no           NUMBER(5)     NOT NULL,
    work_spec_code    VARCHAR2(50)  NOT NULL,
    description       VARCHAR2(200),
    duration_minutes  NUMBER(5),
    required_skill    VARCHAR2(50)
);

CREATE INDEX idx_wos_work_order ON work_order_spec (work_order_id);

-- See data.sql for INSERT statements; the syntax is portable between
-- Oracle and H2 for this simple table, so the same inserts work against
-- a real Oracle instance too.
